# -*- coding: utf-8 -*-
"""Persona.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfRzf5_asLk8PViARkecvRXjfG2Jp8CF
"""

!pip install praw --quiet
import logging
logging.getLogger("praw").setLevel(logging.ERROR)

import praw

reddit = praw.Reddit(
    client_id="8RNsm7uy-KzMuZtfwtwtMg",  # from your screenshot
    client_secret="w4nW6HYfrc3YsZQ0JXZr9WrSEE4wLA",
    user_agent="script:reddit.persona:v1.0 (by u/Satyam)"
)

print("✅ Reddit Login Successful:", reddit.read_only)

def fetch_user_data(username):
    user = reddit.redditor(username)
    comments, posts = [], []

    try:
        for c in user.comments.new(limit=100):
            comments.append((c.body, f"https://reddit.com{c.permalink}"))
        for p in user.submissions.new(limit=50):
            content = p.title + "\n" + p.selftext
            posts.append((content, f"https://reddit.com{p.permalink}"))
    except Exception as e:
        print("❌ Error fetching user data:", e)

    return comments, posts

import re

def analyze_persona(comments, posts):
    persona = {
        "traits": [],
        "interests": [],
        "opinions": [],
        "citations": []
    }

    keywords = ["I believe", "I think", "In my opinion", "I feel", "I love", "My favorite"]

    for text, link in comments + posts:
        lower = text.lower()

        if any(k.lower() in lower for k in keywords):
            if "believe" in lower or "think" in lower:
                persona["opinions"].append((text, link))
            elif "love" in lower or "favorite" in lower:
                persona["interests"].append((text, link))

        if re.search(r"\b(curious|friendly|sarcastic|kind|thoughtful)\b", lower):
            persona["traits"].append((text, link))

    persona["citations"] = list(set([link for _, link in comments + posts][:10]))

    return persona

def save_persona(username, persona):
    filename = f"{username}.txt"

    output = f"USER: {username}\n\n--- PERSONA ---\n\n"

    output += "👤 Personality Traits:\n"
    for t in persona["traits"]:
        output += f"- {t[0]} [Source: {t[1]}]\n"

    output += "\n📚 Interests:\n"
    for i in persona["interests"]:
        output += f"- {i[0]} [Source: {i[1]}]\n"

    output += "\n🎯 Opinions:\n"
    for o in persona["opinions"]:
        output += f"- {o[0]} [Source: {o[1]}]\n"

    output += "\n🔗 Source References:\n"
    for c in persona["citations"]:
        output += f"- {c}\n"

    # ✅ Print it in notebook
    print(output)

    # 💾 Save to file
    with open(filename, "w", encoding="utf-8") as f:
        f.write(output)

    print(f"\n✅ Persona saved to: {filename}")
    return filename

def run_persona_generator():
    url = input("🔗 Enter Reddit profile URL: ").strip()
    username = url.rstrip('/').split('/')[-1]

    print(f"\n⏳ Fetching data for: {username}...\n")
    comments, posts = fetch_user_data(username)

    if not comments and not posts:
        print("⚠️ No data found.")
        return

    persona = analyze_persona(comments, posts)
    filename = save_persona(username, persona)

    return filename

filename = run_persona_generator()

from google.colab import files
files.download(filename)